# Generated by Django 5.1.2 on 2024-11-02 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255, verbose_name='Street Address')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('state', models.CharField(max_length=255, verbose_name='state')),
                ('zipcode', models.IntegerField(max_length=9, verbose_name='zipcode')),
            ],
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Immunization name')),
                ('date_given', models.DateField(verbose_name='Date immunization given')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason for immunization given')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Farmer Name')),
                ('phone_number', models.IntegerField(max_length=10, verbose_name='Phone Number')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Farm Name')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pigs.address')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='pigs.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Pig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Pig Name')),
                ('temperature', models.IntegerField(max_length=5, verbose_name='Temperature')),
                ('weight', models.IntegerField(max_length=5, verbose_name='Temperature')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='pigs.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Past_Farm_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrived', models.DateField(verbose_name='Date Arrived')),
                ('date_departed', models.DateField(verbose_name='Date Departed')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_farm_records', to='pigs.farm')),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_pig_records', to='pigs.pig')),
            ],
        ),
    ]
