# Generated by Django 5.1.2 on 2024-11-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.IntegerField(verbose_name='zipcode'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone_number',
            field=models.IntegerField(verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='pig',
            name='temperature',
            field=models.IntegerField(verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='pig',
            name='weight',
            field=models.IntegerField(verbose_name='Temperature'),
        ),
    ]
