# Generated by Django 5.1.2 on 2024-11-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0002_alter_address_zipcode_alter_farmer_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='address',
        ),
        migrations.AddField(
            model_name='farm',
            name='city',
            field=models.CharField(default='Seward', max_length=255, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='farm',
            name='state',
            field=models.CharField(default='Nebraska', max_length=255, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='farm',
            name='street_address',
            field=models.CharField(default='800 N Columbia Ave', max_length=255, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='farm',
            name='zipcode',
            field=models.IntegerField(default='12345', verbose_name='zipcode'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
