# Generated by Django 5.1.2 on 2024-11-02 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0003_remove_farm_address_farm_city_farm_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunization',
            name='pig',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, related_name='pigs', to='pigs.pig'),
        ),
        migrations.AlterField(
            model_name='pig',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Pig Tag Number'),
        ),
        migrations.AlterField(
            model_name='pig',
            name='temperature',
            field=models.FloatField(verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='pig',
            name='weight',
            field=models.IntegerField(verbose_name='Weight'),
        ),
    ]
