# Generated by Django 5.1.2 on 2024-11-02 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigs', '0004_immunization_pig_alter_pig_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunization',
            name='pig',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, related_name='pigs', to='pigs.pig'),
        ),
    ]
